version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: feedback-db
    environment:
      POSTGRES_DB: feedback_intelligence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      # Initialize schema on first run (simplified schema without pgvector)
      - ./backend/database/schema_simple.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d feedback_intelligence || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: feedback-backend
    env_file:
      - backend/.env
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: feedback_intelligence
      DB_SSL: "false"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3000"
    # Optional: persist logs to host
    # volumes:
    #   - ./backend/logs:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    container_name: feedback-frontend
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db-data:
